version: '3.9'
services:
  portainer:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access existing docker environment on local host
      - /var/lib/docker/volumes:/var/lib/docker/volumes # Access existing docker volumes on local host

volumes:
  portainer_data:
