version: '3.9'
services:
  database:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access existing docker environment on local host
      - portainer_data:/data # Save portainer data persistently
    healthcheck:
      test: ["CMD", "curl" ,"-f", "http://localhost:9443/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  portainer_data:
